#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
( cd "$SCRIPT_DIR/applications/solvers/compressible/rhoHyperFoam" && ./Allclean || true )
( cd "$SCRIPT_DIR/libraries/timeIntegrators" && wclean libso || true )
( cd "$SCRIPT_DIR/libraries/numFlux" && wclean libso || true )
echo "[Allclean] Done."
